### ISSUE TITLE
cannot instal on node-red

### ISSUE THREAD

**Issue by RogierQ** [urbiworx/node-red-contrib-midi#4]
Trying to install it on raspberry pi with node red
`22 May 13:22:01 - [warn] ------------------------------------------
22 May 13:22:01 - [warn] Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-midi@1.0.1
In file included from ../src/node-midi.cpp:6:0:
../src/lib/RtMidi/RtMidi.cpp:1095:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
make: *** [Release/obj.target/midi/src/node-midi.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.41-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/midi
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN grunt-coffeelint@0.0.16 requires a peer of grunt@>=0.4.0 but none was installed.
npm WARN grunt-contrib-coffee@1.0.0 requires a peer of grunt@>= 0.4.5 but none was installed.
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm ERR! Linux 4.9.41-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "--save-prefix=\"~\"" "--production" "node-red-contrib-midi@1.0.1"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! midi@0.9.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@0.9.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the midi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs midi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls midi
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
22 May 13:22:01 - [warn] ------------------------------------------
`

**Comment by lighthousebulb** [comment]
The same here. Any solutions?

**Comment by shanness** [comment]
According to this you need to install libasound2-dev , have alsa running, and have a C++ compiler installed (probs already is).

https://www.npmjs.com/package/midi

**Comment by gregberger** [comment]
The version of node midi referenced in the package.json has compatibility issues with raspberry pi : node-gyp is unable the recompile.

There's a pending PR fixing that ( #11 ) but hasn't been merged.

What I did is : forked the repo; fixed the dependency version for `midi` in package.json and installed the package directly from my fork. It worked

See [this SO post](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) to install package directly from GIthub

**Comment by hpc32** [comment]
> The version of node midi referenced in the package.json has compatibility issues with raspberry pi : node-gyp is unable the recompile.
> 
> There's a pending PR fixing that ( #11 ) but hasn't been merged.
> 
> What I did is : forked the repo; fixed the dependency version for `midi` in package.json and installed the package directly from my fork. It worked
> 
> See [this SO post](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly) to install package directly from GIthub

Thanks a lot for your help and advice! Now installs without issue.

**Comment by HonestJohn61** [comment]
Hi @gregberger and @hpc32 

I see you have a workaround, but can you explain in bit more detail please? I'm pretty new to Linux so forking the repo and fixing the dependency make sense, but I have no idea how to do that! Thanks

**Comment by natcl** [comment]
This should now be fixed, let me know if it works !

**Comment by AaronD-GH** [comment]
From a user's perspective, the problem still exists.  Installing `libasound2-dev` as noted above does fix it, but you have to come here to see that.  For those who use Node Red to get away from "complicated" build systems, and just click the Install button in the UI's Palette Manager, "it's just broken" with little hope of rescue:

```
-----------------------------------------------------------
2025-07-25T17:15:53.782Z Install : node-red-contrib-midi 1.1.2

2025-07-25T17:15:53.785Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-midi@1.1.2
2025-07-25T17:15:54.864Z [err] npm error code 1
2025-07-25T17:15:54.865Z [err] npm error path /home/aaron/.node-red/node_modules/midi
2025-07-25T17:15:54.865Z [err] npm error command failed
2025-07-25T17:15:54.865Z [err] npm error command sh -c node-gyp rebuild
2025-07-25T17:15:54.865Z [err] npm error make: Entering directory '/home/aaron/.node-red/node_modules/midi/build'
2025-07-25T17:15:54.865Z [err] npm error   CXX(target) Release/obj.target/midi/vendor/rtmidi/RtMidi.o
2025-07-25T17:15:54.865Z [err] npm error make: Leaving directory '/home/aaron/.node-red/node_modules/midi/build'
2025-07-25T17:15:54.865Z [err] npm error gyp info it worked if it ends with ok
2025-07-25T17:15:54.865Z [err] npm error gyp info using node-gyp@10.1.0
2025-07-25T17:15:54.865Z [err] npm error gyp info using node@20.19.4 | linux | x64
2025-07-25T17:15:54.865Z [err] npm error gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn /usr/bin/python3
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args [
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args 'binding.gyp',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-f',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args 'make',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-I',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '/home/aaron/.node-red/node_modules/midi/build/config.gypi',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-I',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-I',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '/home/aaron/.cache/node-gyp/20.19.4/include/node/common.gypi',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dlibrary=shared_library',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dvisibility=default',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dnode_root_dir=/home/aaron/.cache/node-gyp/20.19.4',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dnode_lib_file=/home/aaron/.cache/node-gyp/20.19.4/<(target_arch)/node.lib',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dmodule_root_dir=/home/aaron/.node-red/node_modules/midi',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Dnode_engine=v8',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '--depth=.',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '--no-parallel',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '--generator-output',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args 'build',
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args '-Goutput_dir=.'
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args ]
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn make
2025-07-25T17:15:54.865Z [err] npm error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
2025-07-25T17:15:54.865Z [err] npm error ../vendor/rtmidi/RtMidi.cpp:1543:10: fatal error: alsa/asoundlib.h: No such file or directory
2025-07-25T17:15:54.865Z [err] npm error  1543 | #include <alsa/asoundlib.h>
2025-07-25T17:15:54.865Z [err] npm error       |          ^~~~~~~~~~~~~~~~~~
2025-07-25T17:15:54.865Z [err] npm error compilation terminated.
2025-07-25T17:15:54.865Z [err] npm error make: *** [midi.target.mk:115: Release/obj.target/midi/vendor/rtmidi/RtMidi.o] Error 1
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! build error 
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! stack Error: `make` failed with exit code: 2
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! System Linux 6.8.0-64-lowlatency
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! cwd /home/aaron/.node-red/node_modules/midi
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! node -v v20.19.4
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! node-gyp -v v10.1.0
2025-07-25T17:15:54.865Z [err] npm error gyp ERR! not ok
2025-07-25T17:15:54.867Z [err] npm error A complete log of this run can be found in: /home/aaron/.npm/_logs/2025-07-25T17_15_53_864Z-debug-0.log
2025-07-25T17:15:54.873Z rc=1
```

Could that install possibly be done automatically?  Or perhaps check for it up front and put instructions in the log, instead of cluttering it with trying to work anyway and failing?
